### ISSUE TITLE
Cloning a List<T> via cloneRec doesn't append the last element and also does not set rear.

### ISSUE THREAD

**Issue by medium-endian** [medium-endian/DynamicDatastructures#1]

**Comment by triolenzunge** [comment]
The method 'clone' does this ok, but I would like it to work recursively too.

**Comment by medium-endian** [comment]
This is how the bug happens:
node.cloneRec() does work correctly. However, it doesn't set the rear pointer to the last element.
makeRear did nothing when last.next was null, assuming that the rear pointer was correct...
